[build]
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Optimize for Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Function configuration for better serverless performance
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@prisma/client", "@prisma/engines"]